table Product
	lineageTag: cc4ef520-2db4-42b7-8345-4abc2e2eac20

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 98b2d0a1-958e-4fc5-bcb7-bcd02a900725
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = User

	column ProductName
		dataType: string
		lineageTag: f7f8933b-4edd-45ba-90f4-29adedf15741
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column 'Standard Cost'
		dataType: double
		lineageTag: 976c3a2c-b353-467c-91cc-9c796b8e9d8f
		summarizeBy: none
		sourceColumn: Standard Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Color
		dataType: string
		lineageTag: 21bbd1fe-6012-4a44-bc64-bd5b96b7470f
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 59a2e878-6b0c-40c3-9498-e13822fec39b
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9c75e4dd-728a-4974-b423-37df2f86cd4a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Background Color Format'
		dataType: string
		lineageTag: 9c9219e9-c1b4-4ca9-9069-2b0c4862be73
		summarizeBy: none
		sourceColumn: Background Color Format

		annotation SummarizationSetBy = Automatic

	column 'Font Color Format'
		dataType: string
		lineageTag: 70785431-4609-4db7-bdaf-376497dd6616
		summarizeBy: none
		sourceColumn: Font Color Format

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ramakrishnan\EXCEL DATASETS COURSERA\Product.xlsx"), null, true),
				    Product_Sheet = Source{[Item="Product",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Product_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"Product", type text}, {"Standard Cost", type number}, {"Color", type text}, {"Subcategory", type text}, {"Category", type text}, {"Background Color Format", type text}, {"Font Color Format", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Product", "ProductName"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

